apiVersion: batch/v1
kind: CronJob
metadata:
  name: scrape-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scraper
              image: ghcr.io/onemorebyte/scrape-metacritic:{{ default .Chart.AppVersion .Values.image.tag }}
              imagePullPolicy: IfNotPresent
              env:
                - name: wumbo
                  valueFrom:
                    secretKeyRef:
                      name: aaa
                      key: aaa
          restartPolicy: OnFailure
